# Generated by Django 4.0.1 on 2022-01-29 20:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0002_alter_bugs_assigned_on_alter_bugs_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='assigned_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 30, 1, 41, 25, 355867), null=True),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 30, 1, 41, 25, 355867)),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='raised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='resolved_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 30, 1, 41, 25, 355867)),
        ),
    ]
