# Generated by Django 4.0.1 on 2022-01-29 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_alter_bugs_assigned_on_alter_bugs_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='assigned_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 30, 2, 4, 4, 702600), null=True),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 30, 2, 4, 4, 702600)),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='raised_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='resolved_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 30, 2, 4, 4, 702600)),
        ),
    ]
