# Generated by Django 4.0.1 on 2022-01-29 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_alter_bugs_assigned_on_alter_bugs_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='assigned_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 30, 2, 7, 52, 817348), null=True),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 30, 2, 7, 52, 817348)),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='resolved_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 30, 2, 7, 52, 817348)),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='severity_level',
            field=models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low'), ('NS', 'Not Yet Set')], default='NS', max_length=4),
        ),
    ]
