# Generated by Django 4.0.1 on 2022-01-29 21:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0006_alter_bugs_assigned_on_alter_bugs_deadline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField(blank=True)),
                ('severity_level', models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low'), ('NS', 'Not Yet Set')], default='NS', max_length=4)),
                ('resolved', models.BooleanField(default=False)),
                ('deadline', models.DateTimeField(default=datetime.datetime(2022, 1, 30, 2, 36, 3, 277585))),
                ('raised_by', models.CharField(blank=True, max_length=150, null=True)),
                ('visibility', models.IntegerField(default=1)),
                ('resolved_on', models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 30, 2, 36, 3, 277585))),
                ('opened_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_on', models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 30, 2, 36, 3, 277585), null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignedperson', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Bugs',
        ),
    ]
