# Generated by Django 4.0.1 on 2022-01-29 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_bug_delete_bugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='assigned_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 30, 2, 48, 49, 856801), null=True),
        ),
        migrations.AlterField(
            model_name='bug',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 30, 2, 48, 49, 856801)),
        ),
        migrations.AlterField(
            model_name='bug',
            name='resolved_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 30, 2, 48, 49, 856801)),
        ),
    ]
